// Generated by CoffeeScript 1.10.0
(function() {
  window.Application = function() {
    var aM;
    aM = {
      csonify: function(obj, indent) {
        var key, prefix, value;
        indent = indent ? indent + 1 : 1;
        prefix = Array(indent).join('  ');
        if (typeof obj === 'string') {
          return ' "' + obj + '"';
        }
        if (typeof obj !== 'object') {
          return ' ' + obj;
        }
        if (Array.isArray(obj)) {
          return ' [' + ((function() {
            var i, len, results;
            results = [];
            for (i = 0, len = obj.length; i < len; i++) {
              value = obj[i];
              results.push(aM.csonify(value));
            }
            return results;
          })()).join(',') + ' ]';
        }
        return ((function() {
          var results;
          results = [];
          for (key in obj) {
            value = obj[key];
            results.push('\n' + prefix + '"' + key + '":' + aM.csonify(value, indent));
          }
          return results;
        })()).join('');
      }
    };
    return {
      init: function() {
        return $.getJSON('http://localhost:3000/users.json').done(function(data) {
          return $('#work-space').loadTemplate($('#users-table'), {}, {
            afterInsert: function() {
              return $('#users-list').loadTemplate($('#user'), data);
            }
          });
        });
      },
      test_stub: function() {
        return $.getJSON('http://localhost:3000/users.json').done(function(data) {
          return $('#work-space').loadTemplate($('#users-table'), {}, {
            afterInsert: function() {
              return $('#users-list').loadTemplate($('#user'), data);
            }
          });
        });
      }
    };
  };

}).call(this);
