// Generated by CoffeeScript 1.10.0
(function() {
  $.getJSON('http://localhost:3000/users.json').done(function(data) {
    return $('#work-space').loadTemplate('templates/users_table.html', {}, {
      afterInsert: function() {
        return $('#users-list').loadTemplate('templates/user.html', data);
      }
    });
  });

  $.ajax({
    type: 'PUT',
    url: 'http://localhost:3000/users/5.json',
    data: {
      user: {
        username: 'user_alala'
      }
    },
    beforeSend: function(xhr) {
      return xhr.setRequestHeader("Authorization", "Basic " + btoa("admin:passwork"));
    }
  }).done(function(data) {
    return console.log(data);
  }).fail(function(xhr, s) {
    console.log(xhr.status);
    return console.log(xhr.responseText);
  });

}).call(this);
