language: node_js  
node_js:  
  - "0.10"
before_install:  
  - npm install
  - npm install -g grunt-cli
addons:
  code_climate:
    repo_token: dd25299e579f9e71de8eb6dc300400a821326210e6693da02897e524650e7947
after_script:
  - codeclimate-test-reporter < lcov.info