// Generated by CoffeeScript 1.10.0
(function() {
  describe('Application', function() {
    beforeEach(function() {
      this.app = new Application();
      return setFixtures(fixtures);
    });
    return it('testable, its templates loadable, its AJAX calls mockable!', function() {
      var doneFn;
      spyOn($, 'getJSON').and.callFake(function(r) {
        var d;
        d = $.Deferred();
        d.resolve(requests.users);
        return d.promise();
      });
      doneFn = jasmine.createSpy('done');
      $.when(this.app.init()).done(function(data) {
        return doneFn(data);
      });
      expect(doneFn).toHaveBeenCalled();
      expect($('#work-space tbody#users-list tr td')[0]).toBeInDOM();
      return expect($('#work-space tbody#users-list tr').length).toEqual(4);
    });
  });

}).call(this);
